//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入登录账号(邮箱地址).
        /// </summary>
        public static string account_info {
            get {
                return ResourceManager.GetString("account_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string btn_ok {
            get {
                return ResourceManager.GetString("btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击更换头像.
        /// </summary>
        public static string chang_head {
            get {
                return ResourceManager.GetString("chang_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聊天.
        /// </summary>
        public static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入邮箱地址.
        /// </summary>
        public static string email_input {
            get {
                return ResourceManager.GetString("email_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 果断退出.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找回密码.
        /// </summary>
        public static string find_pwd {
            get {
                return ResourceManager.GetString("find_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忘记密码?.
        /// </summary>
        public static string forget_pwd {
            get {
                return ResourceManager.GetString("forget_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再来一局.
        /// </summary>
        public static string game_again {
            get {
                return ResourceManager.GetString("game_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏说明.
        /// </summary>
        public static string game_describe {
            get {
                return ResourceManager.GetString("game_describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏大厅.
        /// </summary>
        public static string game_hall {
            get {
                return ResourceManager.GetString("game_hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 众游三人象棋.
        /// </summary>
        public static string game_name {
            get {
                return ResourceManager.GetString("game_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏大厅.
        /// </summary>
        public static string gamehall_no {
            get {
                return ResourceManager.GetString("gamehall_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已满.
        /// </summary>
        public static string hall_state_full {
            get {
                return ResourceManager.GetString("hall_state_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未满.
        /// </summary>
        public static string hall_state_Not_full {
            get {
                return ResourceManager.GetString("hall_state_Not_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史消息(0).
        /// </summary>
        public static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时.
        /// </summary>
        public static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登 录.
        /// </summary>
        public static string Login_name {
            get {
                return ResourceManager.GetString("Login_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消息.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分.
        /// </summary>
        public static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昵称:.
        /// </summary>
        public static string nickname {
            get {
                return ResourceManager.GetString("nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有账号?.
        /// </summary>
        public static string no_account {
            get {
                return ResourceManager.GetString("no_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知.
        /// </summary>
        public static string notify {
            get {
                return ResourceManager.GetString("notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 呼~~ 暂时没有新消息哦~·~.
        /// </summary>
        public static string notify_msg {
            get {
                return ResourceManager.GetString("notify_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入密码.
        /// </summary>
        public static string paswd_info {
            get {
                return ResourceManager.GetString("paswd_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电话.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人资料.
        /// </summary>
        public static string private_info {
            get {
                return ResourceManager.GetString("private_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快速开始.
        /// </summary>
        public static string quick_start {
            get {
                return ResourceManager.GetString("quick_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住密码.
        /// </summary>
        public static string record_pwd {
            get {
                return ResourceManager.GetString("record_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立即注册.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 积分:.
        /// </summary>
        public static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 积分等级.
        /// </summary>
        public static string score_level {
            get {
                return ResourceManager.GetString("score_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 积分说明：注册送100积分；赢一局10积分；输一局-10积分；和棋不扣分；.
        /// </summary>
        public static string score_note {
            get {
                return ResourceManager.GetString("score_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        public static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送.
        /// </summary>
        public static string send_msg {
            get {
                return ResourceManager.GetString("send_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 步时.
        /// </summary>
        public static string single_time {
            get {
                return ResourceManager.GetString("single_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快点儿啊，我等得花儿都谢了！.
        /// </summary>
        public static string tips_come_on {
            get {
                return ResourceManager.GetString("tips_come_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好不容易吃掉一家,^_^.
        /// </summary>
        public static string tips_flaunt {
            get {
                return ResourceManager.GetString("tips_flaunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 真是浪费时间!.
        /// </summary>
        public static string tips_lose_heart {
            get {
                return ResourceManager.GetString("tips_lose_heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你简直太Niubility了！.
        /// </summary>
        public static string tips_niubi {
            get {
                return ResourceManager.GetString("tips_niubi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 真是高手啊!.
        /// </summary>
        public static string tips_praise {
            get {
                return ResourceManager.GetString("tips_praise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 局时.
        /// </summary>
        public static string total_time {
            get {
                return ResourceManager.GetString("total_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未绑定.
        /// </summary>
        public static string unbind {
            get {
                return ResourceManager.GetString("unbind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
