//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入用户名.
        /// </summary>
        public static string account_info {
            get {
                return ResourceManager.GetString("account_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入邮箱地址.
        /// </summary>
        public static string email_input {
            get {
                return ResourceManager.GetString("email_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找回密码.
        /// </summary>
        public static string find_pwd {
            get {
                return ResourceManager.GetString("find_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忘记密码?.
        /// </summary>
        public static string forget_pwd {
            get {
                return ResourceManager.GetString("forget_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏说明.
        /// </summary>
        public static string game_describe {
            get {
                return ResourceManager.GetString("game_describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏大厅.
        /// </summary>
        public static string game_hall {
            get {
                return ResourceManager.GetString("game_hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三人中国象棋.
        /// </summary>
        public static string game_name {
            get {
                return ResourceManager.GetString("game_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏大厅.
        /// </summary>
        public static string gamehall_no {
            get {
                return ResourceManager.GetString("gamehall_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (99/99)已满.
        /// </summary>
        public static string hall_state_full {
            get {
                return ResourceManager.GetString("hall_state_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (33/99)未满.
        /// </summary>
        public static string hall_state_Not_full {
            get {
                return ResourceManager.GetString("hall_state_Not_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登 录.
        /// </summary>
        public static string Login_name {
            get {
                return ResourceManager.GetString("Login_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入密码.
        /// </summary>
        public static string paswd_info {
            get {
                return ResourceManager.GetString("paswd_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快速开始.
        /// </summary>
        public static string quick_start {
            get {
                return ResourceManager.GetString("quick_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立即注册.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
    }
}
